package com.vroom.dbmodel.orm;
// Generated Nov 3, 2018 3:28:54 AM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Addresses generated by hbm2java
 */
@Entity
@Table(name="addresses"
    ,catalog="yaqeen"
)
public class Addresses  implements java.io.Serializable {


     private int id;
     private String street;
     private String city;
     private Integer pin;

    public Addresses() {
    }

	
    public Addresses(int id, String street) {
        this.id = id;
        this.street = street;
    }
    public Addresses(int id, String street, String city, Integer pin) {
       this.id = id;
       this.street = street;
       this.city = city;
       this.pin = pin;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="street", nullable=false, length=100)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="city", length=100)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="pin")
    public Integer getPin() {
        return this.pin;
    }
    
    public void setPin(Integer pin) {
        this.pin = pin;
    }




}


