package com.vroom.dbmodel.orm;
// Generated Nov 17, 2018 5:55:35 PM by Hibernate Tools 5.2.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clienttype generated by hbm2java
 */
@Entity
@Table(name="clienttype")
public class Clienttype  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Boolean isdeleted;

    public Clienttype() {
    }

	
    public Clienttype(String type) {
        this.type = type;
    }
    public Clienttype(String type, Boolean isdeleted, Set<Client> clients) {
       this.type = type;
       this.isdeleted = isdeleted;
     }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false, length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

}


