package com.vroom.dbmodel.orm;
// Generated Nov 3, 2018 3:28:54 AM by Hibernate Tools 5.2.0.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Databasechangelog generated by hbm2java
 */
@Entity
@Table(name="databasechangelog"
    ,catalog="yaqeen"
)
public class Databasechangelog  implements java.io.Serializable {


     private DatabasechangelogId id;

    public Databasechangelog() {
    }

    public Databasechangelog(DatabasechangelogId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="author", column=@Column(name="AUTHOR", nullable=false) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", nullable=false) ), 
        @AttributeOverride(name="dateexecuted", column=@Column(name="DATEEXECUTED", nullable=false, length=19) ), 
        @AttributeOverride(name="orderexecuted", column=@Column(name="ORDEREXECUTED", nullable=false) ), 
        @AttributeOverride(name="exectype", column=@Column(name="EXECTYPE", nullable=false, length=10) ), 
        @AttributeOverride(name="md5sum", column=@Column(name="MD5SUM", length=35) ), 
        @AttributeOverride(name="description", column=@Column(name="DESCRIPTION") ), 
        @AttributeOverride(name="comments", column=@Column(name="COMMENTS") ), 
        @AttributeOverride(name="tag", column=@Column(name="TAG") ), 
        @AttributeOverride(name="liquibase", column=@Column(name="LIQUIBASE", length=20) ), 
        @AttributeOverride(name="contexts", column=@Column(name="CONTEXTS") ), 
        @AttributeOverride(name="labels", column=@Column(name="LABELS") ), 
        @AttributeOverride(name="deploymentId", column=@Column(name="DEPLOYMENT_ID", length=10) ) } )
    public DatabasechangelogId getId() {
        return this.id;
    }
    
    public void setId(DatabasechangelogId id) {
        this.id = id;
    }




}


