package com.vroom.dbmodel.orm;
// Generated Feb 2, 2019 11:12:54 AM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import javax.persistence.Entity;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Grndetail generated by hbm2java
 */
@Entity
@Table(name="grndetail")
public class Grndetail  implements java.io.Serializable {


     private Integer id;
     private Grnmaster grnmaster;
    private Product product;
     private int quantity;
     private double amount;
     private Boolean isdeleted;

    public Grndetail() {
    }

	
    public Grndetail(Grnmaster grnmaster, Product product, int quantity, double amount) {
        this.grnmaster = grnmaster;
        this.product = product;
        this.quantity = quantity;
        this.amount = amount;
    }
    public Grndetail(Grnmaster grnmaster, Product product, int quantity, double amount, Boolean isdeleted) {
       this.grnmaster = grnmaster;
       this.product = product;
       this.quantity = quantity;
       this.amount = amount;
       this.isdeleted = isdeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grnid", nullable=false)
    @JsonIgnore
    public Grnmaster getGrnmaster() {
        return this.grnmaster;
    }
    
    public void setGrnmaster(Grnmaster grnmaster) {
        this.grnmaster = grnmaster;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productid")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="amount", nullable=false, precision=22, scale=0)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }
}


