package com.vroom.dbmodel.orm;
// Generated Dec 6, 2018 6:30:33 AM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vroom.dataservice.inventory.TransactionType;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name="inventory"
    ,catalog="yaqeen"
)
public class Inventory  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private Integer referenceId;
     private Integer inventoryTypeId;
     private Integer activityTypeId;
     private TransactionType transactionType;
     private Integer regionId;
     private Integer insertedByUserId;
     private Date insertedTime;
     private Integer quantity;

    public Inventory() {
    }

    public Inventory(Product product, Integer referenceId, Integer inventoryTypeId, Integer activityTypeId, TransactionType transactionType, Integer regionId, Integer insertedByUserId, Date insertedTime, Integer quantity) {
       this.product = product;
       this.referenceId = referenceId;
       this.inventoryTypeId = inventoryTypeId;
       this.activityTypeId = activityTypeId;
       this.transactionType = transactionType;
       this.regionId = regionId;
       this.insertedByUserId = insertedByUserId;
       this.insertedTime = insertedTime;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productid")
    @JsonIgnore
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="referenceid")
    public Integer getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(Integer referenceId) {
        this.referenceId = referenceId;
    }

    
    @Column(name="inventorytypeid")
    public Integer getInventoryTypeId() {
        return this.inventoryTypeId;
    }
    
    public void setInventoryTypeId(Integer inventoryTypeId) {
        this.inventoryTypeId = inventoryTypeId;
    }

    
    @Column(name="activitytypeid")
    public Integer getActivityTypeId() {
        return this.activityTypeId;
    }
    
    public void setActivityTypeId(Integer activityTypeId) {
        this.activityTypeId = activityTypeId;
    }

    
    @Column(name="transactiontypeid")
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }

    
    @Column(name="regionid")
    public Integer getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    
    @Column(name="insertedbyuserid")
    public Integer getInsertedByUserId() {
        return this.insertedByUserId;
    }
    
    public void setInsertedByUserId(Integer insertedByUserId) {
        this.insertedByUserId = insertedByUserId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="insertedtime", length=10)
    public Date getInsertedTime() {
        return this.insertedTime;
    }
    
    public void setInsertedTime(Date insertedTime) {
        this.insertedTime = insertedTime;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


