package com.vroom.dbmodel.orm;
// Generated Dec 6, 2018 6:30:33 AM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vroom.dataservice.common.InventoryType;
import com.vroom.dataservice.common.ReferenceType;
import com.vroom.dataservice.inventory.TransactionType;
import com.vroom.dataservice.common.Region;

import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name="inventory")
public class Inventory  implements java.io.Serializable {


     private Integer id;
     private Product product;

    @Enumerated
    @Column(columnDefinition = "int")
     private ReferenceType referenceType;

    @Enumerated
    @Column(columnDefinition = "int")
     private InventoryType inventoryType;

    @Enumerated
    @Column(columnDefinition = "int")
     private TransactionType transactionType;

    @Enumerated
    @Column(columnDefinition = "int")
     private Region region;
     private Integer insertedByUserId;
     private Date insertedTime;
     private Integer quantity;

    public Inventory() {
    }

    public Inventory(Product product, ReferenceType referenceType, InventoryType inventoryType, TransactionType transactionType, Region region, Integer insertedByUserId, Date insertedTime, Integer quantity) {
       this.product = product;
       this.referenceType = referenceType;
       this.inventoryType = inventoryType;
       this.transactionType = transactionType;
       this.region = region;
       this.insertedByUserId = insertedByUserId;
       this.insertedTime = insertedTime;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productid")
    @JsonIgnore
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="referenceid")
    public ReferenceType getReferenceType() {
        return this.referenceType;
    }
    
    public void setReferenceType(ReferenceType referenceType) {
        this.referenceType = referenceType;
    }

    
    @Column(name="inventorytypeid")
    public InventoryType getInventoryType() {
        return this.inventoryType;
    }
    
    public void setInventoryType(InventoryType inventoryType) {
        this.inventoryType = inventoryType;
    }
    
    @Column(name="transactiontypeid")
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }

    
    @Column(name="regionid")
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }

    
    @Column(name="insertedbyuserid")
    public Integer getInsertedByUserId() {
        return this.insertedByUserId;
    }
    
    public void setInsertedByUserId(Integer insertedByUserId) {
        this.insertedByUserId = insertedByUserId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="insertedtime", length=10)
    public Date getInsertedTime() {
        return this.insertedTime;
    }
    
    public void setInsertedTime(Date insertedTime) {
        this.insertedTime = insertedTime;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}


