package com.vroom.dbmodel.orm;
// Generated Nov 20, 2018 10:37:48 PM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name="language"
    ,catalog="yaqeen"
)
public class Language  implements java.io.Serializable {


     private Integer id;
     private String language;

    @Column(name="languagecode", nullable=false, length=2)
    public String getLanguagecode() {
        return languagecode;
    }

    public void setLanguagecode(String languagecode) {
        this.languagecode = languagecode;
    }

    private String languagecode;
     private Boolean isdeleted;

    public Language() {
    }

	
    public Language(String language) {
        this.language = language;
    }
    public Language(String language, Boolean isdeleted) {
       this.language = language;
       this.isdeleted = isdeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="language", nullable=false, length=50)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }




}


