package com.vroom.dbmodel.orm;
// Generated Apr 23, 2019 8:20:19 AM by Hibernate Tools 5.2.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name="modules")
public class Modules  implements java.io.Serializable {


     private Integer id;
     private String moduleName;
     private boolean isdeleted;
     private Set<Modulepermissions> modulepermissionses = new HashSet<Modulepermissions>(0);

    public Modules() {
    }

	
    public Modules(String moduleName, boolean isdeleted) {
        this.moduleName = moduleName;
        this.isdeleted = isdeleted;
    }
    public Modules(String moduleName, boolean isdeleted, Set<Modulepermissions> modulepermissionses) {
       this.moduleName = moduleName;
       this.isdeleted = isdeleted;
       this.modulepermissionses = modulepermissionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="moduleName", nullable=false, length=50)
    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    
    @Column(name="isdeleted", nullable=false)
    public boolean isIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<Modulepermissions> getModulepermissionses() {
        return this.modulepermissionses;
    }
    
    public void setModulepermissionses(Set<Modulepermissions> modulepermissionses) {
        this.modulepermissionses = modulepermissionses;
    }
}


