package com.vroom.dbmodel.orm;
// Generated Nov 20, 2018 10:37:48 PM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PaperQuality generated by hbm2java
 */
@Entity
@Table(name="paperquality"
    ,catalog="yaqeen"
)
public class PaperQuality implements java.io.Serializable {


     private Integer id;
     private String name;
     private Boolean isdeleted;

    public PaperQuality() {
    }

	
    public PaperQuality(String name) {
        this.name = name;
    }
    public PaperQuality(String pagequality, Boolean isdeleted) {
       this.name = name;
       this.isdeleted = isdeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }




}


