package com.vroom.dbmodel.orm;
// Generated Nov 28, 2018 9:06:06 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.OnDeleteAction;

import javax.persistence.*;
import javax.persistence.Entity;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Podetail generated by hbm2java
 */
@Entity
@Table(name="podetail"
    ,catalog="yaqeen"
)
public class Podetail  implements java.io.Serializable {


    private Integer id;
    private Pomaster pomaster;
    private Integer productid;
    private Integer quantity;

    public Podetail() {
    }

    public Podetail(Pomaster pomaster, Integer productid, Integer quantity) {
        this.pomaster = pomaster;
        this.productid = productid;
        this.quantity = quantity;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="poid", nullable=false)
    @JsonIgnore
    public Pomaster getPomaster() {
        return this.pomaster;
    }

    public void setPomaster(Pomaster pomaster) {
        this.pomaster = pomaster;
    }


    @Column(name="productid")
    public Integer getProductid() {
        return this.productid;
    }

    public void setProductid(Integer productid) {
        this.productid = productid;
    }


    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}
