package com.vroom.dbmodel.orm;
// Generated Nov 28, 2018 9:06:06 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonFormat;
import org.apache.commons.lang3.time.DateFormatUtils;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.persistence.Entity;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Pomaster generated by hbm2java
 */
@Entity
@Table(name="pomaster"
    ,catalog="yaqeen"
)
public class Pomaster  implements java.io.Serializable {
     private Integer id;
     private Users users;
     private Vendor vendor;
     private Integer modifiedbyuserid;
     private Date modifiedtime;
     private Date insertedtime;
     private Boolean isdeleted;

    @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
    private Set<Postatus> postatus = new HashSet<>(0);

    @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
     private Set<Podetail> podetail = new HashSet<>(0);

    @OneToMany(cascade = CascadeType.ALL,
            mappedBy="pomaster")
    public Set<Postatus> getPostatus(){
       return this.postatus;
    }

    public void setPostatus(Set<Postatus> postatus){
        this.postatus = postatus;
    }

    @OneToMany(cascade = CascadeType.ALL,
            mappedBy="pomaster")
    public Set<Podetail> getPodetail(){
        return this.podetail;
    }

    public void setPodetail(Set<Podetail> podetail){
        this.podetail = podetail;
    }

    public Pomaster() {
    }

	
    public Pomaster(Users users, Vendor vendor) {
        this.users = users;
        this.vendor = vendor;
    }
    public Pomaster(Users users, Vendor vendor, Integer modifiedbyuserid, Date modifiedtime, Date insertedtime, Boolean isdeleted) {
       this.users = users;
       this.vendor = vendor;
       this.modifiedbyuserid = modifiedbyuserid;
       this.modifiedtime = modifiedtime;
       this.insertedtime = insertedtime;
       this.isdeleted = isdeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userid", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendorid", nullable=false)
    public Vendor getVendor() {
        return this.vendor;
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    
    @Column(name="modifiedbyuserid")
    public Integer getModifiedbyuserid() {
        return this.modifiedbyuserid;
    }
    
    public void setModifiedbyuserid(Integer modifiedbyuserid) {
        this.modifiedbyuserid = modifiedbyuserid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modifiedtime", length=10)
    public Date getModifiedtime() {
        return this.modifiedtime;
    }
    
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="insertedtime", length=10)
    public Date getInsertedtime() {
        return this.insertedtime;
    }
    
    public void setInsertedtime(Date insertedtime) {
        this.insertedtime = insertedtime;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Transient
    public String getPoId(){
        return "PO-" + this.getId() + "-" + DateFormatUtils.format(this.insertedtime, "yyyy");
    }
}


