package com.vroom.dbmodel.orm;
// Generated Nov 28, 2018 9:06:06 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Postatustype generated by hbm2java
 */
@Entity
@Table(name="postatustype"
    ,catalog="yaqeen"
)
public class Postatustype  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Boolean isdeleted;

    public Postatustype() {
    }

	
    public Postatustype(String name) {
        this.name = name;
    }
    public Postatustype(String name, Boolean isdeleted) {
       this.name = name;
       this.isdeleted = isdeleted;
     }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }


}


