package com.vroom.dbmodel.orm;
// Generated Nov 28, 2018 9:06:06 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Postatus generated by hbm2java
 */
@Entity
@Table(name="postatus"
    ,catalog="yaqeen"
)
public class Postatus  implements java.io.Serializable {


     private Integer id;
     private Pomaster pomaster;
     private Integer postatusid;
     private Boolean isactive;
     private Integer modifiedbyuserid;
     private Date modifiedtime;

    public Postatus() {
    }

    public Postatus(Pomaster pomaster, Integer postatusid, Boolean isactive, Integer modifiedbyuserid, Date modifiedtime) {
       this.pomaster = pomaster;
       this.postatusid = postatusid;
       this.isactive = isactive;
       this.modifiedbyuserid = modifiedbyuserid;
       this.modifiedtime = modifiedtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="poid", nullable=false)
    @JsonIgnore
    public Pomaster getPomaster() {
        return this.pomaster;
    }
    
    public void setPomaster(Pomaster pomaster) {
        this.pomaster = pomaster;
    }

    
    @Column(name="postatusid")
    public Integer getPostatusid() {
        return this.postatusid;
    }
    
    public void setPostatusid(Integer postatusid) {
        this.postatusid = postatusid;
    }

    
    @Column(name="isactive")
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    
    @Column(name="modifiedbyuserid")
    public Integer getModifiedbyuserid() {
        return this.modifiedbyuserid;
    }
    
    public void setModifiedbyuserid(Integer modifiedbyuserid) {
        this.modifiedbyuserid = modifiedbyuserid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modifiedtime", length=10)
    public Date getModifiedtime() {
        return this.modifiedtime;
    }
    
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }




}


