package com.vroom.dbmodel.orm;
// Generated Nov 3, 2018 3:28:54 AM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="region"
)
public class Region  implements java.io.Serializable {


     private Integer id;
     private String regionname;
     private Boolean isdeleted;

    public Region() {
    }

	
    public Region(String regionname) {
        this.regionname = regionname;
    }
    public Region(String regionname, Boolean isdeleted) {
       this.regionname = regionname;
       this.isdeleted = isdeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="regionname", nullable=false, length=128)
    public String getRegionname() {
        return this.regionname;
    }
    
    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }




}


