package com.vroom.dbmodel.orm;
// Generated Apr 25, 2019 12:36:16 AM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Rolepermisiion generated by hbm2java
 */
@Entity
@Table(name="rolepermission"

)
public class Rolepermission implements java.io.Serializable {


     private Integer roleid;
     private Modulepermissions modulepermissions;
     private Userrole userrole;

    public Rolepermission() {
    }

    public Rolepermission(Modulepermissions modulepermissions, Userrole userrole) {
       this.modulepermissions = modulepermissions;
       this.userrole = userrole;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="userrole"))@Id @GeneratedValue(generator="generator")

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="permissionTypeId", nullable=false)
    public Modulepermissions getModulepermissions() {
        return this.modulepermissions;
    }
    
    public void setModulepermissions(Modulepermissions modulepermissions) {
        this.modulepermissions = modulepermissions;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="roleid", nullable=false)
    @JsonIgnore
    public Userrole getUserrole() {
        return this.userrole;
    }
    
    public void setUserrole(Userrole userrole) {
        this.userrole = userrole;
    }




}


