package com.vroom.dbmodel.orm;
// Generated Dec 16, 2018 5:36:11 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import javax.persistence.Entity;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Todetail generated by hbm2java
 */
@Entity
@Table(name="todetail"
    ,catalog="yaqeen"
)
public class Todetail  implements java.io.Serializable {


     private Integer id;
     private Tomaster toMaster;
     private Product product;
     private Integer quantity;

    public Todetail() {
    }

    public Todetail(Tomaster toMaster, Product product, Integer quantity) {
       this.toMaster = toMaster;
       this.product = product;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="toid", nullable=false)
    @JsonIgnore
    public Tomaster getToMaster() {
        return this.toMaster;
    }
    
    public void setToMaster(Tomaster toMaster) {
        this.toMaster = toMaster;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productid", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

}


