package com.vroom.dbmodel.orm;
// Generated Dec 16, 2018 5:36:11 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Tostatus generated by hbm2java
 */
@Entity
@Table(name="tostatus"
    ,catalog="yaqeen"
)
public class Tostatus  implements java.io.Serializable {


     private Integer id;
     private Tomaster toMaster;
     private Postatustype tostatusType;
     private Boolean isactive;
     private Integer modifiedbyuserid;
     private Date modifiedtime;

    public Tostatus() {
    }

    public Tostatus(Tomaster toMaster, Postatustype tostatusType, Boolean isactive, Integer modifiedbyuserid, Date modifiedtime) {
       this.toMaster = toMaster;
       this.tostatusType = tostatusType;
       this.isactive = isactive;
       this.modifiedbyuserid = modifiedbyuserid;
       this.modifiedtime = modifiedtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="toid", nullable=false)
    @JsonIgnore
    public Tomaster getToMaster() {
        return this.toMaster;
    }

    public void setToMaster(Tomaster toMaster) {
        this.toMaster = toMaster;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tostatusid", nullable=false)
    public Postatustype getTostatusType() {
        return this.tostatusType;
    }

    public void setTostatusType(Postatustype tostatusType) {
        this.tostatusType = tostatusType;
    }

    
    @Column(name="isactive")
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    
    @Column(name="modifiedbyuserid")
    public Integer getModifiedbyuserid() {
        return this.modifiedbyuserid;
    }
    
    public void setModifiedbyuserid(Integer modifiedbyuserid) {
        this.modifiedbyuserid = modifiedbyuserid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modifiedtime", length=10)
    public Date getModifiedtime() {
        return this.modifiedtime;
    }
    
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }




}


