package com.vroom.dbmodel.orm;
// Generated Nov 3, 2018 3:28:54 AM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="yaqeen"
)
public class Users  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private Integer phone;
     private int address;
     private String username;
     private String password;

    public Users() {
    }

	
    public Users(int id, String name, int address) {
        this.id = id;
        this.name = name;
        this.address = address;
    }
    public Users(int id, String name, String email, Integer phone, int address, String username, String password) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.phone = phone;
       this.address = address;
       this.username = username;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone")
    public Integer getPhone() {
        return this.phone;
    }
    
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    
    @Column(name="address", nullable=false)
    public int getAddress() {
        return this.address;
    }
    
    public void setAddress(int address) {
        this.address = address;
    }

    
    @Column(name="username", length=256)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=1024)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


