package com.vroom.dbmodel.orm;
// Generated Apr 25, 2019 12:36:16 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Set;
import javax.persistence.OneToMany;
/**
 * Userrole generated by hbm2java
 */
@Entity
@Table(name="userrole"
)
public class Userrole  implements java.io.Serializable {


    private Integer id;
    private String roleName;
    private Boolean isDeleted;
    private Date insertedtime;
    private Integer insertedbyuserid;
    private Integer modifiedbyuserid;
    private Date modifiedtime;
    private Set<Rolepermission> rolepermisiion;

    public Userrole() {
    }


    public Userrole(String roleName) {
        this.roleName = roleName;
    }

    public Userrole(String roleName, Boolean isDeleted, Date insertedtime, Integer insertedbyuserid, Integer modifiedbyuserid, Date modifiedtime, Set<Rolepermission> rolepermisiion) {
        this.roleName = roleName;
        this.isDeleted = isDeleted;
        this.insertedtime = insertedtime;
        this.insertedbyuserid = insertedbyuserid;
        this.modifiedbyuserid = modifiedbyuserid;
        this.modifiedtime = modifiedtime;
        this.rolepermisiion = rolepermisiion;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "roleName", nullable = false, length = 50)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }


    @Column(name = "isDeleted")
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "insertedtime", length = 10)
    public Date getInsertedtime() {
        return this.insertedtime;
    }

    public void setInsertedtime(Date insertedtime) {
        this.insertedtime = insertedtime;
    }


    @Column(name = "insertedbyuserid")
    public Integer getInsertedbyuserid() {
        return this.insertedbyuserid;
    }

    public void setInsertedbyuserid(Integer insertedbyuserid) {
        this.insertedbyuserid = insertedbyuserid;
    }


    @Column(name = "modifiedbyuserid")
    public Integer getModifiedbyuserid() {
        return this.modifiedbyuserid;
    }

    public void setModifiedbyuserid(Integer modifiedbyuserid) {
        this.modifiedbyuserid = modifiedbyuserid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "modifiedtime", length = 10)
    public Date getModifiedtime() {
        return this.modifiedtime;
    }

    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }




    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userrole")
    public Set<Rolepermission> getRolepermisiion() {
        return this.rolepermisiion;
    }

    public void setRolepermisiion(Set<Rolepermission> rolepermisiion) {
        this.rolepermisiion = rolepermisiion;

    }



}