package com.vroom.dbmodel.orm;
// Generated Nov 15, 2018 11:07:58 PM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vendortype generated by hbm2java
 */
@Entity
@Table(name="vendortype"
)
public class Vendortype  extends AbstractEntity {


     private Integer id;
     private String type;
    private Boolean isdeleted = Boolean.FALSE;

    public Vendortype() {
    }

    public Vendortype(String type) {
       this.type = type;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false, length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }


    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

}


