package com.vroom.dbmodel.orm;
// Generated Nov 3, 2018 3:28:54 AM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vendorcategory generated by hbm2java
 */
@Entity
@Table(name="vendorcategory"
)
public class Vendorcategory  implements java.io.Serializable {


     private Integer id;
     private String categoryname;
     private Boolean isdeleted;

    public Vendorcategory() {
    }

	
    public Vendorcategory(String categoryname) {
        this.categoryname = categoryname;
    }
    public Vendorcategory(String categoryname, Boolean isdeleted) {
       this.categoryname = categoryname;
       this.isdeleted = isdeleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="categoryname", nullable=false, length=128)
    public String getCategoryname() {
        return this.categoryname;
    }
    
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }

    
    @Column(name="isdeleted")
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }




}


