package com.vroom.orm;
// Generated Oct 28, 2018 2:03:02 AM by Hibernate Tools 5.2.0.Final


import org.json.JSONObject;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.HashMap;
import java.util.Map;

/**
 * Addresses generated by hbm2java
 */
@Entity
@Table(name="addresses"
    ,catalog="yaqeen"
)
public class Addresses  implements java.io.Serializable {


     private int id;
     private String street;
     private String city;
     private Integer pin;

    public Addresses() {
    }

	
    public Addresses(int id, String street) {
        this.id = id;
        this.street = street;
    }
    public Addresses(int id, String street, String city, Integer pin) {
       this.id = id;
       this.street = street;
       this.city = city;
       this.pin = pin;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="street", nullable=false, length=100)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="city", length=100)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="pin")
    public Integer getPin() {
        return this.pin;
    }
    
    public void setPin(Integer pin) {
        this.pin = pin;
    }


    @Override
    /**
     * returns Object with value
     */
    public String toString(){

        Map<String, String> map = new HashMap<>(0);
        map.put("street",street );
        map.put("name", Integer.valueOf(id).toString());
        map.put("city",city );
        map.put("pin",Integer.valueOf(pin).toString());

        return new JSONObject(map).toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (!(obj instanceof Addresses))
            return false;
        if (obj == this)
            return true;
        return this.getId() == ((Addresses) obj).getId();
    }

    @Override
    public int hashCode() {
        return this.toString().hashCode();
    }

}


