package com.vroom.orm;
// Generated Oct 28, 2018 2:03:02 AM by Hibernate Tools 5.2.0.Final


import javax.persistence.*;
import java.util.Date;

/**
 * Databasechangeloglock generated by hbm2java
 */
@Entity
@Table(name="databasechangeloglock"
    ,catalog="yaqeen"
)
public class Databasechangeloglock  implements java.io.Serializable {


     private int id;
     private boolean locked;
     private Date lockgranted;
     private String lockedby;

    public Databasechangeloglock() {
    }

	
    public Databasechangeloglock(int id, boolean locked) {
        this.id = id;
        this.locked = locked;
    }
    public Databasechangeloglock(int id, boolean locked, Date lockgranted, String lockedby) {
       this.id = id;
       this.locked = locked;
       this.lockgranted = lockgranted;
       this.lockedby = lockedby;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="LOCKED", nullable=false)
    public boolean isLocked() {
        return this.locked;
    }
    
    public void setLocked(boolean locked) {
        this.locked = locked;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LOCKGRANTED", length=19)
    public Date getLockgranted() {
        return this.lockgranted;
    }
    
    public void setLockgranted(Date lockgranted) {
        this.lockgranted = lockgranted;
    }

    
    @Column(name="LOCKEDBY")
    public String getLockedby() {
        return this.lockedby;
    }
    
    public void setLockedby(String lockedby) {
        this.lockedby = lockedby;
    }




}


