package com.vroom.orm;
// Generated Oct 28, 2018 2:03:02 AM by Hibernate Tools 5.2.0.Final


import org.json.JSONObject;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.HashMap;
import java.util.Map;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="yaqeen"
)
public class Users  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private Integer phone;
     private int address;
     private String username;
     private String password;

    public Users() {
    }

	
    public Users(int id, String name, int address) {
        this.id = id;
        this.name = name;
        this.address = address;
    }
    public Users(int id, String name, String email, Integer phone, int address, String username, String password) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.phone = phone;
       this.address = address;
       this.username = username;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone")
    public Integer getPhone() {
        return this.phone;
    }
    
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    
    @Column(name="address", nullable=false)
    public int getAddress() {
        return this.address;
    }
    
    public void setAddress(int address) {
        this.address = address;
    }

    
    @Column(name="username", length=256)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=1024)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    /**
     * returns Object with value
     */
    public String toString(){

        Map<String, String> map = new HashMap<>(0);
        map.put("name",name );
        map.put("id", Integer.valueOf(id).toString());
        map.put("username",username );
        map.put("email",email );
        map.put("address",Integer.valueOf(address).toString());
        map.put("phone",phone.toString());


        return new JSONObject(map).toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (!(obj instanceof Users))
            return false;
        if (obj == this)
            return true;
        return this.getId() == ((Users) obj).getId();
    }

    @Override
    public int hashCode() {
        return this.toString().hashCode();
    }
}


