package com.vroom.dataservice.inventory;

public enum  TransactionType {
    PURCHASE_GENERATED,
    PURCHASE_CANCELLED,
    PARTIAL_PO_CLOSURE,
    PARTIAL_PO_CLOSURE_REVERSAL,
    PURCHASE_INVENTORY_RETURN,
    INVENTORY_ADDITION,
    INVENTORY_DEDUCTION,
    INVENTORY_WRITE_OFF,
    INVENTORY_TRANSFER_IN,
    INVENTORY_TRANSFER_OUT,
    SALE_GENERATED,
    SALE_CANCELLED,
    PARTIAL_SO_CLOSURE,
    PARTIAL_SO_CLOSURE_REVERSAL,
    SALE_INVENTORY_RETURN,
    INVENTORY_TRANSITION;

}
